### ISSUE TITLE
Emacs.app: dylibs not loaded

### ISSUE THREAD

**Issue by tzudot** [renard/emacs-build-macosx#1]
Firstly, thank you for putting them all together in this script. It very neatly generates Emacs.app, within the DMG. This works fine when I launch Emacs.app on the same computer but when deployed on a different computer, it fails to load the dylibs, such as, libMagickWand-6.Q16HDRI.2.dylib, libMagickCore-6.Q16HDRI.2.dylib, libgnutls.28.dylib, and etc.

As a workaround, I had to symlink the libraries from `/Applications/Emacs.app/Contents/Resources/lib` to `/usr/local/lib`.

What is the way to configure emacs to use the bundled libraries? On the same computer, after placing `Emacs.app` into `/Applications`, on a second attempt, I have tried to pass on 
`LDFLAGS=-L/Applications/Emacs.app/Contents/Resources/lib` and `LIBS` assigned to various libraries but that did not work.

**Comment by renard** [comment]
Thanks for the comment.

Can you please confirm it works now for you?

Cheers.

**Comment by tzudot** [comment]
I can confirm that this change fixes my reported issue. ✔️ Cheers.

**Comment by tzudot** [comment]
Fix a minor annoyance in the output file name.

```
From 5069a24a5b6388a82bfdac59c439b6ebbb2a93d8 Mon Sep 17 00:00:00 2001
From: Tzu Dot <tzudot@gmail.com>
Date: Sat, 24 Jan 2015 05:29:07 -0800
Subject: [PATCH 1/1] remove unneeded closing parenthesis in VNUM.

---
 build-emacs | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/build-emacs b/build-emacs
index a571169..521640b 100755
--- a/build-emacs
+++ b/build-emacs
@@ -44,7 +44,7 @@ STRINGS="

 DAY=`date -u -r $TIMESTAMP +"%Y-%m-%d_%H-%M-%S"`
 ORIG=`grep ^AC_INIT configure.ac`
-VNUM=`echo $ORIG | cut -d, -f2 | sed 's/ //g'`
+VNUM=`echo $ORIG | cut -d, -f2 | sed 's/[ )]//g'`
 VERS="$DAY Git $REV"
 DESCR="Emacs_Cocoa_${VNUM}_${DAY}_Git_${REV}"

-- 
1.9.3 (Apple Git-50)
```

**Comment by renard** [comment]
Is that patch really necessary?

can you please provide an example of what it fix?

My output file is: `Emacs_Cocoa_25.0.50_2015-01-23_00-50-15_Git_f02406c.dmg`

**Comment by tzudot** [comment]
My output file,
Before making the change: Emacs_Cocoa_24.4**)**_2014-10-20_19-21-15_Git_83bad90.dmg
After making the change: Emacs_Cocoa_24.4_2014-10-20_19-21-15_Git_83bad90.dmg

**Comment by renard** [comment]
Yep you're right, since Fri Mar 28 19:11:39 2014 (7b207d6d4f2de3ee07ffc8b02464c2b186372970) `AC_INIT` has changed.

I slightly improve your submission in 78b6c5a.

Let me know if you still experience issues.

**Comment by tzudot** [comment]
Excellent. It works. 👍
